[colors]
foreground = "#f9fbff"
background = "#292b3c"
cursor_bg = "#f9fbff"
cursor_border = "#f9fbff"
cursor_fg = "#292b3c"
selection_bg = "#3b3d4d"
selection_fg = "#f9fbff"

ansi = ["#212230", "#fe4c4c", "#65ff91", "#ffc965", "#7fa7ff", "#b58cd8", "#7fe7ff", "#e6e7e9"]
brights = ["#8d8e9a", "#fe4c4c", "#65ff91", "#ffc965", "#7fa7ff", "#b58cd8", "#7fe7ff", "#f9fbff"]

[colors.tab_bar]
inactive_tab_edge = "#222434"
background = "#191b28"

[colors.tab_bar.active_tab]
fg_color = "#7fa7ff"
bg_color = "#292b3c"

[colors.tab_bar.inactive_tab]
bg_color = "#222434"
fg_color = "#b9bac0"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#222434"
fg_color = "#7fa7ff"

[colors.tab_bar.new_tab_hover]
bg_color = "#222434"
bg_color = "#7fa7ff"

[colors.tab_bar.new_tab]
fg_color = "#7fa7ff"
bg_color = "#191b28"

[metadata]
aliases = []
author = "pauchiner"
name = "PastelNight High Contrast"