name: Continuous Integration
on: 
  - push
  - pull_request
jobs:
  styles:
    name: 💅 Styles
    if: always()
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Format code
        uses: JohnnyMorganz/stylua-action@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: lua/


      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "styles: auto-format with stylua"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

  extras:
    name: 🎨 Extras
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - styles

    permissions:
      contents: write

  steps:
      - uses: actions/checkout@v3

      - name: Setup Neovim (nightly)
        uses: Neovim/setup@v2
        with:
          neovim-version: nightly

      - name: Build Extras
        run: |
          nvim -u NONE -E -R --headless \
            --cmd "set rtp^=." \
            --cmd "packloadall" \
            --cmd "lua require('pastelnight.extra').setup()" \
            --cmd qa

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): auto-generate extras"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
  docs:
    name: 📔 Docs
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    needs:
      - extras

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - run: git pull
      - name: Generate Docs
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: pastelnight.nvim
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): auto-generate docs"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

  release:
    name: 📦 Release
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - docs

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
      - uses: actions/checkout@v3
      - name: tag stable versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Last Stable Release"
          git push origin stable
